"""Session Reporter — genera report MD per ogni sessione di esecuzione e lo invia a api.noxen.ai."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

import httpx


@dataclass
class SkillUsageRecord:
    skill_name: str
    uses: int
    outcome: str  # success, partial, failed


@dataclass
class SessionReport:
    session_id: str
    license_key: str
    plan: str
    date: str
    project_type: str
    technologies: list[str]
    loc_count: int
    file_count: int

    # Execution
    duration_minutes: float
    goals_total: int
    goals_completed: int
    goals_failed: int
    approval_type: str  # manual, auto, rejected

    # Skills
    skills_used: list[SkillUsageRecord] = field(default_factory=list)
    skills_created: list[str] = field(default_factory=list)

    # LLM
    llm_provider: str = ""
    estimated_tokens: int = 0

    # Errors
    errors: list[str] = field(default_factory=list)

    # Meta
    noxen_version: str = "0.3.0"

    def to_markdown(self) -> str:
        """Genera report in formato Markdown."""
        lines = [
            "# Noxen Session Report",
            "",
            f"**Session ID:** {self.session_id}",
            f"**Date:** {self.date}",
            f"**Plan:** {self.plan}",
            f"**Noxen Version:** {self.noxen_version}",
            "",
            "## Project",
            f"- Type: {self.project_type}",
            f"- Technologies: {', '.join(self.technologies)}",
            f"- Size: {self.loc_count:,} LOC, {self.file_count} files",
            "",
            "## Execution",
            f"- Duration: {self.duration_minutes:.0f} minutes",
            f"- Goals total: {self.goals_total}",
            f"- Goals completed: {self.goals_completed}",
            f"- Goals failed: {self.goals_failed}",
            f"- Approval: {self.approval_type}",
            "",
        ]

        if self.skills_used:
            lines += [
                "## Skills Used",
                "| Skill | Uses | Outcome |",
                "|-------|------|---------|",
            ]
            for s in self.skills_used:
                lines.append(f"| {s.skill_name} | {s.uses} | {s.outcome} |")
            lines.append("")

        if self.skills_created:
            lines += ["## Skills Created"]
            for s in self.skills_created:
                lines.append(f"- {s}")
            lines.append("")

        if self.errors:
            lines += ["## Errors"]
            for e in self.errors:
                lines.append(f"- {e}")
            lines.append("")

        lines += [
            "## LLM",
            f"- Provider: {self.llm_provider}",
            f"- Estimated tokens: {self.estimated_tokens:,}",
            "",
            "---",
            f"*Generated by Noxen v{self.noxen_version}*",
        ]

        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "session_id": self.session_id,
            "license_key": self.license_key,
            "plan": self.plan,
            "date": self.date,
            "project_type": self.project_type,
            "technologies": self.technologies,
            "loc_count": self.loc_count,
            "file_count": self.file_count,
            "duration_minutes": self.duration_minutes,
            "goals_total": self.goals_total,
            "goals_completed": self.goals_completed,
            "goals_failed": self.goals_failed,
            "approval_type": self.approval_type,
            "skills_used": [
                {"name": s.skill_name, "uses": s.uses, "outcome": s.outcome}
                for s in self.skills_used
            ],
            "skills_created": self.skills_created,
            "llm_provider": self.llm_provider,
            "estimated_tokens": self.estimated_tokens,
            "errors": self.errors,
            "noxen_version": self.noxen_version,
        }


class SessionReporter:
    """Invia report di sessione a api.noxen.ai e li salva localmente come backup."""

    def __init__(
        self,
        license_server_url: str,
        license_key: str,
        reports_dir: str = "data/reports",
    ):
        self._server = license_server_url
        self._key = license_key
        self._reports_dir = Path(reports_dir)
        self._reports_dir.mkdir(parents=True, exist_ok=True)

    async def send(self, report: SessionReport) -> bool:
        """Salva report localmente e lo invia al server. Ritorna True se inviato."""
        # Salva sempre in locale
        report_path = self._reports_dir / f"{report.session_id}.md"
        report_path.write_text(report.to_markdown())

        # Invia al server
        try:
            async with httpx.AsyncClient() as client:
                r = await client.post(
                    f"{self._server}/v1/sessions/report",
                    json=report.to_dict(),
                    timeout=30.0,
                )
                return r.status_code == 200
        except Exception:
            # Silenzioso — il report e' gia' salvato in locale
            return False
